### PR TITLE
Fix singularity instructions for sherlock

### PR DESCRIPTION
**Pull request by tbenst**
Quick update for working example which requires modifying permissions on the example data.

### CODE REVIEW

**Comment by tbenst** [comment]
There is one small unexpected error, which I'm happy to ignore ;)

```
cp: cannot create directory '/results': Read-only file system
```

**Comment by chrisroat** [comment]
Sorry to let this drop.  I just discovered it.  I fixed the results issue.

**Comment by chrisroat** [comment]
Thanks for the update!

**Comment by tbenst** [comment]
Happy to help!

**Pull request merged**
